import { SurahMeta } from './types';

export const JUZ_AMMA_SURAHS: SurahMeta[] = [
  { number: 78, name: "An-Naba", englishName: "The Tidings", verseCount: 40, meaning: "Berita Besar" },
  { number: 79, name: "An-Nazi'at", englishName: "Those Who Drag Forth", verseCount: 46, meaning: "Malaikat Pencabut" },
  { number: 80, name: "Abasa", englishName: "He Frowned", verseCount: 42, meaning: "Ia Bermuka Masam" },
  { number: 81, name: "At-Takwir", englishName: "The Overthrowing", verseCount: 29, meaning: "Menggulung" },
  { number: 82, name: "Al-Infitar", englishName: "The Cleaving", verseCount: 19, meaning: "Terbelah" },
  { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", verseCount: 36, meaning: "Orang-orang Curang" },
  { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", verseCount: 25, meaning: "Terbelah" },
  { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", verseCount: 22, meaning: "Gugusan Bintang" },
  { number: 86, name: "At-Tariq", englishName: "The Morning Star", verseCount: 17, meaning: "Yang Datang di Malam Hari" },
  { number: 87, name: "Al-A'la", englishName: "The Most High", verseCount: 19, meaning: "Yang Paling Tinggi" },
  { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", verseCount: 26, meaning: "Hari Pembalasan" },
  { number: 89, name: "Al-Fajr", englishName: "The Dawn", verseCount: 30, meaning: "Fajar" },
  { number: 90, name: "Al-Balad", englishName: "The City", verseCount: 20, meaning: "Negeri" },
  { number: 91, name: "Ash-Shams", englishName: "The Sun", verseCount: 15, meaning: "Matahari" },
  { number: 92, name: "Al-Lail", englishName: "The Night", verseCount: 21, meaning: "Malam" },
  { number: 93, name: "Ad-Duha", englishName: "The Morning Hours", verseCount: 11, meaning: "Waktu Dhuha" },
  { number: 94, name: "Ash-Sharh", englishName: "The Relief", verseCount: 8, meaning: "Melapangkan" },
  { number: 95, name: "At-Tin", englishName: "The Fig", verseCount: 8, meaning: "Buah Tin" },
  { number: 96, name: "Al-Alaq", englishName: "The Clot", verseCount: 19, meaning: "Segumpal Darah" },
  { number: 97, name: "Al-Qadr", englishName: "The Power", verseCount: 5, meaning: "Kemuliaan" },
  { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", verseCount: 8, meaning: "Bukti" },
  { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", verseCount: 8, meaning: "Kegoncangan" },
  { number: 100, name: "Al-Adiyat", englishName: "The Courser", verseCount: 11, meaning: "Kuda Perang" },
  { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", verseCount: 11, meaning: "Hari Kiamat" },
  { number: 102, name: "At-Takathur", englishName: "The Rivalry in World Increase", verseCount: 8, meaning: "Bermegah-megahan" },
  { number: 103, name: "Al-Asr", englishName: "The Declining Day", verseCount: 3, meaning: "Masa" },
  { number: 104, name: "Al-Humazah", englishName: "The Traducer", verseCount: 9, meaning: "Pengumpat" },
  { number: 105, name: "Al-Fil", englishName: "The Elephant", verseCount: 5, meaning: "Gajah" },
  { number: 106, name: "Quraish", englishName: "Quraysh", verseCount: 4, meaning: "Suku Quraisy" },
  { number: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses", verseCount: 7, meaning: "Barang-barang Berguna" },
  { number: 108, name: "Al-Kawthar", englishName: "The Abundance", verseCount: 3, meaning: "Nikmat Berlimpah" },
  { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", verseCount: 6, meaning: "Orang-orang Kafir" },
  { number: 110, name: "An-Nasr", englishName: "The Succour", verseCount: 3, meaning: "Pertolongan" },
  { number: 111, name: "Al-Masad", englishName: "The Palm Fibre", verseCount: 5, meaning: "Gejolak Api" },
  { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", verseCount: 4, meaning: "Ikhlas" },
  { number: 113, name: "Al-Falaq", englishName: "The Daybreak", verseCount: 5, meaning: "Waktu Subuh" },
  { number: 114, name: "An-Nas", englishName: "The Mankind", verseCount: 6, meaning: "Manusia" }
];